version: '2'
services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - ./cards:/opt/solr/server/solr/mycores/cards
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - cards